name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AZURE_REGISTRY: ennatuurlijkscraperregistry
      ACR_REPO_NAME: scraper
      ROOT_FOLDER: scraper

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Azure Container Registry login
        run: |
          az acr login --name $AZURE_REGISTRY

      - name: Build and push Docker image
        run: |
          cd $ROOT_FOLDER
          IMAGE_URI=$AZURE_REGISTRY.azurecr.io/$ACR_REPO_NAME:latest
          docker build \
            -t $IMAGE_URI \
            --build-arg AZURE_SERVICE_BUS_QUEUE_NAME=${{ secrets.AZURE_SERVICE_BUS_QUEUE_NAME }} \
            --build-arg AZURE_SERVICE_BUS_CONNECTION_STRING=${{ secrets.AZURE_SERVICE_BUS_CONNECTION_STRING }} \
            .
          docker push $IMAGE_URI
